### ISSUE TITLE
`agg_population_qc_tables` ValueError: "Cannot mask with non-boolean array containing NA / NaN values"

### ISSUE THREAD

**Issue by jaamarks** [NCI-CGR/GwasQcPipeline#365]
**Description**
A collaborator reached out about an error they were encountering during a run of the GwasQcPipeline. In particular, they provided the following error message:
```
/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/bin/python3.8 /rds/project/rds-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/.snakemake/scripts/tmp775ng_t0.agg_population_qc_tables.py
Traceback (most recent call last):
  File "/rds/project/rds-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/.snakemake/scripts/tmp775ng_t0.agg_population_qc_tables.py", line 158, in <module>
    main(**defaults)
  File "/rds/project/rds-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/.snakemake/scripts/tmp775ng_t0.agg_population_qc_tables.py", line 100, in main
    gwas_df = create_gwas(df)
  File "/rds/project/rds-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/.snakemake/scripts/tmp775ng_t0.agg_population_qc_tables.py", line 134, in create_gwas
    temp_df = temp_df.loc[temp_df.case_control.str.contains("case|control"), :]
  File "/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/lib/python3.8/site-packages/pandas/core/indexing.py", line 1097, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/lib/python3.8/site-packages/pandas/core/indexing.py", line 1289, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/lib/python3.8/site-packages/pandas/core/indexing.py", line 955, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/lib/python3.8/site-packages/pandas/core/indexing.py", line 1324, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "/home/jgd29/rds/rds-confluence-9n94GhvEU6U/software/GwasQcPipeline_v1.7.0/conda/envs/GwasQcPipeline/lib/python3.8/site-packages/pandas/core/common.py", line 134, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
[Fri Nov 29 15:05:59 2024]
Error in rule agg_population_qc_tables:
    jobid: 62
    output: subject_level/population_qc.csv, subject_level/gwas.txt
```

As you can see from this error message, the main issue is `ValueError: Cannot mask with non-boolean array containing NA / NaN values`. This is likely coming from the line of code:
```python
temp_df = temp_df.loc[temp_df.case_control.str.contains("case|control"), :]
```

which is in the `agg_population_qc_tables.py` script. 

The case/control information is coming from the `subject_level/subject_qc.csv`, so we suspect that there is an issue with the case/control information for 1 or more subjects in this file. This information comes from the `cgr_sample_qc.csv`.

**Comment by jaamarks** [comment]
We discovered the issue and a work-around solution. The following are emails which the work-around and the origin of the issue.

Here is the email I shared with our collaborator which explains the work-around:
```
Issue
The following files have missing data in the last column (is_extreme_autosomal_heterozygosity):
“subject_level/South_Asian/qc.csv”
“subject_level/ European/qc.csv”
 
Solution
Remove the problematic subjects from those files. For example, we can use awk to remove any subject that does not have True/False in the last column:
                awk -F"," 'NR==1 || $NF == "True" || $NF == "False" { print }' South_Asian/qc.csv > tmp && mv tmp South_Asian/qc.csv
 
Description
There is one subject in the South_Asian/qc.csv that is missing data for the last 5 columns (O_HOM,E_HOM,N_NM,F,is_extreme_autosomal_heterozygosity).
There are 11 subjects in the European/qc.csv that are missing data for the last 5 columns.
 
The last column (is_extreme_autosomal_heterozygosity) is derived from the following code in the population_qc_table.py module
     is_extreme_autosomal_heterozygosity=lambda x: x.F.abs() > threshold
 
So since F is missing, then is_extreme_autosomal_heterozygosity is blank which is causing an error.
So, if you just remove the problematic subjects from these files, then the agg_population_qc_tables rule should complete successfully. I was able to get it to work when ran as a stand-alone step with the data you shared.
```

<br>

Here is the reply email which summarizes the origin of the issue that caused these select subjects to have missing data:
```
The pipeline now completes. Looking at the European qc.csv sorted by SubjectID (as attached) the problem is with the unusually long IDs such as A4YWKE_P_0C7F141405C4F3FEC16DC6A1A57A8C32 (41 characters) At some point that seems to have been truncated to A4YWKE_P_0C7F141405C4F3FEC16DC6A1A57A8C (39 characters) and the entries for that sample are now split been two lines.
These are additional samples that I did not have when I first ran the Cimba samples in summer.
I will make sure not to use long sample IDs in future. Maybe you could add check for very long IDs  to the pre-flight checks.
```

**Comment by jaamarks** [comment]
See issue #366 for future work related to this.
